services:
  frontend:
    build:
      context: ./web-client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      VITE_BACKEND_URL: http://backend:8000
    volumes:
      - ./web-client:/app
      - /app/node_modules

  backend-init:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    working_dir: /app/src
    command: ["python", "-m", "seed"]
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_LOCATION: database
      DB_NAME: postgres
      SEED_FILE: ${SEED_FILE:-/app/seeds/default.sql}
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_LOCATION: database
      DB_NAME: postgres
      JWT_SECRET_KEY: 528482b94c0521c37c2a3c2e749f435c00790e891c076cbe9aafbcc00a546302
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:? "Missing GOOGLE_API_KEY env var"}
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID:? "Missing PLAID_CLIENT_ID env var"}
      PLAID_SECRET: ${PLAID_SECRET:? "Missing PLAID_SECRET env var"}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:? "Missing AWS_ACCESS_KEY_ID env var"}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:? "Missing AWS_SECRET_ACCESS_KEY env var"}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:? "Missing AWS_DEFAULT_REGION env var"}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET:? "Missing AWS_S3_BUCKET env var"}
    depends_on:
      database:
        condition: service_healthy
      backend-init:
        condition: service_completed_successfully
    volumes:
      - ./backend:/app

  database:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
