FROM python:3.12-alpine AS base

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

RUN rm requirements.txt
COPY ./src /app/src
COPY ./seeds /app/seeds

EXPOSE 8000
