name: PyTest

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: write

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.12
              uses: actions/setup-python@v3
              with:
                  python-version: "3.12"
            - name: Install black
              run: |
                  cd backend
                  python -m pip install black
            - name: Format with black
              run: |
                  cd backend
                  black .

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v7

    test:
        needs: format
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.12
              uses: actions/setup-python@v3
              with:
                  python-version: "3.12"
            - name: Install dependencies
              run: |
                  cd backend
                  python -m pip install --upgrade pip
                  pip install flake8 pytest
                  pip install -r requirements.txt
            - name: Test with pytest
              run: |
                  cd backend
                  pytest
