name: PyTest

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.12
              uses: actions/setup-python@v3
              with:
                  python-version: "3.12"
            - name: Install dependencies
              run: |
                  cd backend
                  python -m pip install --upgrade pip
                  pip install pytest black pytest-cov
                  pip install -r requirements.txt
            # TODO - raise coverage bar to 80% eventually
            - name: Test with pytest
              run: |
                  cd backend
                  pytest --cov=./src --cov-fail-under=75
            - name: Check formatting
              run: |
                  cd backend
                  black --check .
