name: ViTest

on:
    push:
        branches: ["main"]
        paths:
            - "web-client/**"
            - ".github/workflows/vitest.yml"
    pull_request:
        branches: ["main"]
        paths:
            - "web-client/**"
            - ".github/workflows/vitest.yml"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
            - name: Install dependencies
              run: |
                  cd web-client
                  npm install
            - name: Run tests
              run: |
                  cd web-client
                  npm test
